## Basic Configuration
baseurl = "/"
languageCode = "en"
relativeurls = true
theme = "hyde-hyde"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

## Hugo Built-in Features
# disqusShortname = ""
# googleAnalytics = ""
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Stefan"
    title = "StatsLab"
    dateformat = "Jan 1, 2006"
    # description = "..."
    #authorimage = "/img/stats.png"
    #authorimage = "/img/8020logo.png"
    authorimage = "/img/logo.jpg"
    highlightjs = true
    # highlightjsstyle = "github"

## Social Accounts
[params.social]
    github = "lurd4862"
    linkedin = "stefan-fouch√®-8a126711a"
    email = "stefan.fouche.ltd@gmail.com?"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about_me/"
[[menu.main]]
    name = "Search by tag"
    identifier = "tags"
    weight = 200
    url = "/tags/"
