## Basic Configuration
baseurl = "/"
languageCode = "en"
relativeurls = true
theme = "hyde-hyde"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

## Hugo Built-in Features
# disqusShortname = ""
# googleAnalytics = ""
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Author"
    title = "Title"
    # description = "..."
    authorimage = "/img/logo.jpg"
    dateformat = "Jan 1, 2006"
    highlightjs = true
    # highlightjsstyle = "github"

## Social Accounts
[params.social]
    github = "<username>"
    instagram = "<username>"
    xing = "<username>"
    linkedin = "<username>"
    twitter = "<username>"
    facebook = "<username>"
    stackoverflow = "<username>"
    email = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
